use_frameworks!

platform :ios, '8.0'

target 'LibDependsOnCwift_Example' do
  pod 'LibDependsOnCwift', :path => '../'

  target 'LibDependsOnCwift_Tests' do
    inherit! :search_paths

    
  end
end
